### PR TITLE
[Unitaryhack] https://github.com/errorcorrectionzoo/eczoo_generator/i…

### PR DESCRIPTION
**Pull request by cometta**
…ssues/6

### CODE REVIEW

**Comment by phfaist** [comment]
Thanks for the pull request!!

Here are a few remaining issues I noticed:

- Please streamline the usage of the script without having to manually paste in a github token ID in the script source. My suggestion is to paste the github token in a file named `ghtoken.SECRET`, to create a `.gitignore` file in this same folder instructing git to ignore that file, and to change the script source as follows:
```diff
-GITHUB_ACCESS_TOKEN = "your access token" # Guide at https://catalyst.zoho.com/help/tutorials/githubbot/generate-access-token.html
+# Guide at https://catalyst.zoho.com/help/tutorials/githubbot/generate-access-token.html
+with open( os.path.join(os.path.dirname(__file__), 'ghtoken.SECRET') ) as f:
+    GITHUB_ACCESS_TOKEN = f.read().strip()
```

- The script does not seem to function correctly. For instance, the surface code (toric code) has multiple contributors, but somehow, only 'phfaist' is detected as contributor. You can do `git log codes/quantum/qubits/surface/surface/surface.yml` and `git log -- codes/quantum/qubits/surface/surface.yml` to see who the contributors are; they should all be listed. It looks like the script never seems to add more than one contributor for some reason. Please make sure the script performs as intended.

- I'm worried about another aspect, too. We do know that some of the `code_id`s have changed in time. How do you handle the detected `code_id`s that are no longer existing? Normally `zoo.get_code(...)` raises an exception for nonexisting `code_id`'s, but when I ran your script, it did not abort with any exception. I'm worried that contributions might be missed by your script, since there are no contributions registered to historical `code_id`s. Actually, from what I see in your script, it looks like the `code_id` is read from the *current* file tree, not the tree at the time of the commit, and that if file name in the historical commit does not happen to exist in the current tree, then the contribution from that authors in that commit is dropped completely! (There is no `else:` to match the `if:` on line 68.) So if I understand your code correctly, authors that committed changes to code files which will have subsequently moved will not be recognized in the contributors field. Please correct this.

- Your code changes the structure, key ordering, and formatting of the original YAML files. The used convention for structuring and formatting the YAML file (choice of quotes, the order of the keys, as well as any comments and whitespace, etc.) should be preserved. This will also help keeping diffs simple after we add the `_meta` field. The simplest way to achieve this is not to dump the data with `yaml.dump()` but to append the relevant information to the end of the YAML file content directly. The additional information should also be formatted using similar conventions; I'd like to use single quoted values for the contributor name.

- Please add a minimal feedback information (e.g., with `logging.debug()`) when iterating over the commits. As is, the script runs for a long time without any feedback on progress, so it's hard to know if it's progressing normally or if it hang for some reason.

- Please implement the proof-of-principle `get_is_change_significant()` as discussed. (Use `git diff --word-diff=porcelain`, and count total character changes associated with the word diff.)

- Please use the name `_meta` for the meta field, not `meta_`.

- The value of the `_meta` field should be a dictionary, not a list; `contributors` should be a key in that dictionary.

- If the contributor does not have any github user name, please do not include the key `githubusername` in the resulting dictionary (as opposed to setting the key to an empty string).

After double-checking with Victor, it actually appears that the same `code_id`'s have been used for different codes across the file tree's history. So please change the script to store the contributor information not only by `code_id` but by tuple `(code_id, code name, code YAML file path in commit)` when iterating through the commits. The code name is value of the `name:` field in the code YAML file. You can ignore the part about updating the code file's YAML content, and instead, please dump the detected information in some usable form (e.g., dump the dictionary `{(code_id, code_name, code_yml_file): [ ... list of contributors... ]}` in whatever reasonable format such as JSON, YAML, or pickle).

Thanks for your contributions!

**Comment by cometta** [comment]
item 3:, i read from the local file structure directly. That way, zoo.get_code() will never miss out any file. The reason i do not read from commit is there is possibility the code_id in commit no longer exist in local file structure 

item 4:  this is possible, if we assume all codes/*.yml file will always never have _meta, contributors field as a pre-requisite to run the script and we do not need to use yml.dump(). to append extra field at the bottom of the yml file.

**Comment by phfaist** [comment]
Can you parse the YAML code of the committed file and extract the `code_id` and `name` from it? The important part is to parse the file contents in the commit (the new committed file with the author's changes) and not try to look up the same file name in the current file tree.

**Comment by cometta** [comment]
@phfaist 

i able to read from commit's content, but some of the yaml file content is invalid and yaml library unable to parse it, for example https://github.com/errorcorrectionzoo/eczoo_data/commit/78b9f6e1ea4cd37fa90ee81639b921967e10620d  search for : name: 'Kitaev's toric code'  , this line is unable to parse by yaml library and thus can't extract code_id for this file

**Comment by phfaist** [comment]
Ah, good point. Can you read out those values using a regex to detect the key (like `^(code_id|name)\s*:\s*(.*)$` with `flags=re.MULTILINE`), then 1) attempt to parse that full line as YAML to extract the value; if the YAML parsing fails, use the captured rest (.*) as the name, after stripping single quotes from the edges of the string and replacing doubled single quotes `''` by a single quote `'`. We can assume that the value for the `code_id:` and `name:` keys are on the same line. Let's assume that `code_id` and `name` are not misspelled and that they have no preceding whitespace on that line. If the keys cannot be found in the YAML contents, please print a warning message with the commit ID and YAML file name so that it can be inspected manually. I'd put this logic into its own separate function, in case we have to further tweak it. I'm open to other suggestions in case you think of a simpler way to address this issue.

**Comment by cometta** [comment]
i do not think i have much bandwidth for this unless we can simplify the requirement

**Pull request closed without merging**
